#Data source name for the database connection.
Dsn: 'dbname=nominatim '

#Path to the folder where rules data are stored (geojson, vector tiles, etc).
RulesFolderPath: 'qa-data'

#Prefix path of the web URL to access the rules data (ex: https://nominatim.org/QA-data).
WebPrefixPath: ''
