name: CI Build-Tests
on: [push, pull_request]
jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pybind11 mypy
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127  --exclude tests,build,__init__.py --extend-ignore=E302,E722 --statistics
    - name: Check typing
      run: mypy
    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install postgresql postgresql-client
        sudo systemctl restart postgresql
        sudo -u postgres createuser -s runner
    - name: Test with pytest
      run: |
        python3 setup.py build
        pytest tests
